name: p
favicon: null
layout_spectrum: 0.6692250764463097
typography_spectrum: 0.9318009747657925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8439737379085273
  lightness: 0.007088892161846161
  saturation: 0.6095890165306628
  rhythmicContrast: 0.01488736760802567
purpose: []
